version: 2
model: null
models:
  - name: core_delegation_updated_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: transaction_hash
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: contract
        data_type: text
      - name: event_name
        data_type: text
      - name: account_id
        data_type: text
      - name: pool_id
        data_type: text
      - name: collateral_type
        data_type: text
      - name: amount
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: leverage
        data_type: numeric
      - name: sender
        data_type: text
  - name: core_vault_collateral_optimism_mainnet
    columns:
      - name: ts
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: block_number
        description: "Block number"
        data_type: bigint
        tests:
          - not_null
      - name: pool_id
        description: "ID of the pool"
        data_type: integer
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: collateral_type
        description: "Type of delegated collateral"
        data_type: character varying
        tests:
          - not_null
      - name: amount
        description: "Collateral amount"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: collateral_value
        description: "Vault collateral value"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: contract_address
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null
  - name: core_vault_debt_optimism_mainnet
    columns:
      - name: ts
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: block_number
        description: "Block number"
        data_type: bigint
        tests:
          - not_null
      - name: pool_id
        description: "ID of the pool"
        data_type: integer
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: collateral_type
        description: "Type of delegated collateral"
        data_type: character varying
        tests:
          - not_null
      - name: debt
        description: "Vault debt"
        data_type: numeric
        tests:
          - not_null
      - name: contract_address
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null