models:
  - name: fct_v2_integrator_daily_optimism_mainnet
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: tracking_code
        data_type: text
      - name: exchange_fees
        data_type: numeric
      - name: exchange_fees_total
        data_type: numeric
      - name: volume
        data_type: numeric
      - name: volume_total
        data_type: numeric
      - name: trades
        data_type: bigint
      - name: trades_total
        data_type: numeric
      - name: traders
        data_type: bigint
      - name: volume_share
        data_type: numeric
      - name: trades_share
        data_type: numeric
      - name: exchange_fees_share
        data_type: numeric
      - name: cumulative_exchange_fees
        data_type: numeric
      - name: cumulative_volume
        data_type: numeric
      - name: cumulative_trades
        data_type: numeric
  - name: fct_v2_integrator_hourly_optimism_mainnet
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: tracking_code
        data_type: text
      - name: exchange_fees
        data_type: numeric
      - name: exchange_fees_total
        data_type: numeric
      - name: volume
        data_type: numeric
      - name: volume_total
        data_type: numeric
      - name: trades
        data_type: bigint
      - name: trades_total
        data_type: numeric
      - name: traders
        data_type: bigint
      - name: volume_share
        data_type: numeric
      - name: trades_share
        data_type: numeric
      - name: exchange_fees_share
        data_type: numeric
      - name: cumulative_exchange_fees
        data_type: numeric
      - name: cumulative_volume
        data_type: numeric
      - name: cumulative_trades
        data_type: numeric
  - name: fct_v2_market_daily_optimism_mainnet
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: market
        data_type: text
      - name: exchange_fees
        data_type: numeric
      - name: liquidation_fees
        data_type: numeric
      - name: volume
        data_type: numeric
      - name: amount_liquidated
        data_type: numeric
      - name: trades
        data_type: bigint
      - name: liquidations
        data_type: bigint
      - name: long_oi_usd
        data_type: numeric
      - name: short_oi_usd
        data_type: numeric
      - name: total_oi_usd
        data_type: numeric
      - name: cumulative_exchange_fees
        data_type: numeric
      - name: cumulative_liquidation_fees
        data_type: numeric
      - name: cumulative_volume
        data_type: numeric
      - name: cumulative_amount_liquidated
        data_type: numeric
      - name: cumulative_trades
        data_type: bigint
      - name: cumulative_liquidations
        data_type: bigint
  - name: fct_v2_market_hourly_optimism_mainnet
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: market
        data_type: text
      - name: exchange_fees
        data_type: numeric
      - name: liquidation_fees
        data_type: numeric
      - name: volume
        data_type: numeric
      - name: amount_liquidated
        data_type: numeric
      - name: trades
        data_type: bigint
      - name: liquidations
        data_type: bigint
      - name: long_oi_usd
        data_type: numeric
      - name: short_oi_usd
        data_type: numeric
      - name: total_oi_usd
        data_type: numeric
      - name: cumulative_exchange_fees
        data_type: numeric
      - name: cumulative_liquidation_fees
        data_type: numeric
      - name: cumulative_volume
        data_type: numeric
      - name: cumulative_amount_liquidated
        data_type: numeric
      - name: cumulative_trades
        data_type: bigint
      - name: cumulative_liquidations
        data_type: bigint
  - name: fct_v2_stats_daily_optimism_mainnet
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: exchange_fees
        data_type: numeric
      - name: liquidation_fees
        data_type: numeric
      - name: volume
        data_type: numeric
      - name: amount_liquidated
        data_type: numeric
      - name: trades
        data_type: numeric
      - name: liquidations
        data_type: numeric
      - name: long_oi_usd
        data_type: numeric
      - name: short_oi_usd
        data_type: numeric
      - name: total_oi_usd
        data_type: numeric
      - name: eth_btc_oi_usd
        data_type: numeric
      - name: alt_oi_usd
        data_type: numeric
      - name: cumulative_exchange_fees
        data_type: numeric
      - name: cumulative_liquidation_fees
        data_type: numeric
      - name: cumulative_volume
        data_type: numeric
      - name: cumulative_amount_liquidated
        data_type: numeric
      - name: cumulative_trades
        data_type: numeric
      - name: cumulative_liquidations
        data_type: numeric
  - name: fct_v2_stats_hourly_optimism_mainnet
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: exchange_fees
        data_type: numeric
      - name: liquidation_fees
        data_type: numeric
      - name: volume
        data_type: numeric
      - name: amount_liquidated
        data_type: numeric
      - name: trades
        data_type: numeric
      - name: liquidations
        data_type: numeric
      - name: long_oi_usd
        data_type: numeric
      - name: short_oi_usd
        data_type: numeric
      - name: total_oi_usd
        data_type: numeric
      - name: eth_btc_oi_usd
        data_type: numeric
      - name: alt_oi_usd
        data_type: numeric
      - name: cumulative_exchange_fees
        data_type: numeric
      - name: cumulative_liquidation_fees
        data_type: numeric
      - name: cumulative_volume
        data_type: numeric
      - name: cumulative_amount_liquidated
        data_type: numeric
      - name: cumulative_trades
        data_type: numeric
      - name: cumulative_liquidations
        data_type: numeric
  - name: fct_v2_actions_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: price
        data_type: numeric
      - name: account
        data_type: text
      - name: market
        data_type: text
      - name: margin
        data_type: numeric
      - name: trade_size
        data_type: numeric
      - name: size
        data_type: numeric
      - name: last_size
        data_type: numeric
      - name: skew
        data_type: numeric
      - name: fee
        data_type: numeric
      - name: order_type
        data_type: text
      - name: tracking_code
        data_type: text
  - name: fct_v2_funding_optimism_mainnet
    columns:
      - name: block_number
        data_type: integer
      - name: market
        data_type: text
      - name: funding_rate
        data_type: numeric
  - name: fct_v2_liquidations_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: price
        data_type: numeric
      - name: account
        data_type: text
      - name: market
        data_type: text
      - name: margin
        data_type: numeric
      - name: trade_size
        data_type: numeric
      - name: size
        data_type: numeric
      - name: last_size
        data_type: numeric
      - name: skew
        data_type: numeric
      - name: fee
        data_type: numeric
      - name: order_type
        data_type: text
      - name: tracking_code
        data_type: text
  - name: fct_v2_market_stats_optimism_mainnet
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: id
        data_type: character varying
      - name: market
        data_type: text
      - name: block_number
        data_type: integer
      - name: funding_rate
        data_type: numeric
      - name: exchange_fees
        data_type: numeric
      - name: liquidation_fees
        data_type: numeric
      - name: volume
        data_type: numeric
      - name: amount_liquidated
        data_type: numeric
      - name: trades
        data_type: integer
      - name: liquidations
        data_type: integer
      - name: tracking_code
        data_type: text
      - name: skew
        data_type: numeric
      - name: long_oi
        data_type: numeric
      - name: short_oi
        data_type: numeric
      - name: total_oi
        data_type: numeric
      - name: long_oi_usd
        data_type: numeric
      - name: short_oi_usd
        data_type: numeric
      - name: total_oi_usd
        data_type: numeric
      - name: long_oi_pct
        data_type: numeric
      - name: short_oi_pct
        data_type: numeric
      - name: cumulative_exchange_fees
        data_type: numeric
      - name: cumulative_liquidation_fees
        data_type: numeric
      - name: cumulative_volume
        data_type: numeric
      - name: cumulative_amount_liquidated
        data_type: numeric
      - name: cumulative_trades
        data_type: bigint
      - name: cumulative_liquidations
        data_type: bigint
  - name: fct_v2_open_interest_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: ts
        data_type: timestamp with time zone
      - name: market
        data_type: text
      - name: order_type
        data_type: text
      - name: trade_size
        data_type: numeric
      - name: price
        data_type: numeric
      - name: skew
        data_type: numeric
      - name: long_oi
        data_type: numeric
      - name: short_oi
        data_type: numeric
      - name: long_oi_pct
        data_type: numeric
      - name: short_oi_pct
        data_type: numeric
      - name: total_oi
        data_type: numeric
      - name: long_oi_usd
        data_type: numeric
      - name: short_oi_usd
        data_type: numeric
      - name: total_oi_usd
        data_type: numeric
  - name: fct_v2_trade_tracking_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: block_number
        data_type: integer
      - name: tracking_code
        data_type: text
  - name: fct_v2_trades_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: price
        data_type: numeric
      - name: account
        data_type: text
      - name: market
        data_type: text
      - name: margin
        data_type: numeric
      - name: trade_size
        data_type: numeric
      - name: size
        data_type: numeric
      - name: last_size
        data_type: numeric
      - name: skew
        data_type: numeric
      - name: fee
        data_type: numeric
      - name: order_type
        data_type: text
      - name: tracking_code
        data_type: text
  - name: fct_v2_transfers_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: transaction_hash
        data_type: text
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: market
        data_type: text
      - name: account
        data_type: text
      - name: margin_delta
        data_type: numeric
      - name: net_market_transfers
        data_type: numeric
      - name: net_transfers
        data_type: numeric
  - name: lt_trades_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: block_number
        data_type: integer
      - name: ts
        data_type: timestamp with time zone
      - name: transaction_hash
        data_type: text
      - name: contract
        data_type: text
      - name: event_name
        data_type: text
      - name: account
        data_type: text
      - name: token
        data_type: text
      - name: market
        data_type: text
      - name: leveraged_token_amount
        data_type: numeric
      - name: base_asset_amount
        data_type: numeric
      - name: price
        data_type: numeric
        tests:
          - not_null
      - name: volume
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
            min_value: 0
            inclusive: true
