network_id: 8453
protocol: "synthetix"

blocks:
  min_block: "7.5M"
  requests_per_second: 1000
  block_increment: 500
  chunk_size: 80

eth_calls:
  - contract_name: "CoreProxy"
    package_name: "system"
    function_name: "getVaultCollateral"
    inputs:
      - [1, "0xC74eA762cF06c9151cE074E6a569a5945b6302E7"]
      - [1, "0x729Ef31D86d31440ecBF49f27F7cD7c16c6616d2"]
    min_block: "7.5M"
    requests_per_second: 1000
    block_increment: 500
    chunk_size: 80

  - contract_name: "CoreProxy"
    package_name: "system"
    function_name: "getVaultDebt"
    inputs:
      - [1, "0xC74eA762cF06c9151cE074E6a569a5945b6302E7"]
      - [1, "0x729Ef31D86d31440ecBF49f27F7cD7c16c6616d2"]
    min_block: "7.5M"
    requests_per_second: 1000
    block_increment: 500
    chunk_size: 80
