blocks:
  network_id: 8453
  min_block: "7.5M"
  requests_per_second: 25

eth_calls:
  - name: "base_mainnet_vault_collateral"
    network_id: 8453
    contract_name: "CoreProxy"
    function_name: "getVaultCollateral"
    inputs:
      - [1, "0xC74eA762cF06c9151cE074E6a569a5945b6302E7"]
    min_block: "7.5M"
    requests_per_second: 25

  - name: "base_mainnet_vault_debt"
    network_id: 8453
    contract_name: "CoreProxy"
    function_name: "getVaultDebt"
    inputs:
      - [1, "0xC74eA762cF06c9151cE074E6a569a5945b6302E7"]
    min_block: "7.5M"
    requests_per_second: 25