network_id: 8453

blocks:
  min_block: "7.5M"
  requests_per_second: 25
  block_increment: 500
  chunk_size: 80

eth_calls:
  - contract_name: "CoreProxy"
    package_name: "system"
    function_name: "getVaultCollateral"
    inputs:
      - [1, "0xC74eA762cF06c9151cE074E6a569a5945b6302E7"]
      - [1, "0x729Ef31D86d31440ecBF49f27F7cD7c16c6616d2"]
    min_block: "7.5M"
    requests_per_second: 25
    block_increment: 500
    chunk_size: 80

  - contract_name: "CoreProxy"
    package_name: "system"
    function_name: "getVaultDebt"
    inputs:
      - [1, "0xC74eA762cF06c9151cE074E6a569a5945b6302E7"]
      - [1, "0x729Ef31D86d31440ecBF49f27F7cD7c16c6616d2"]
    min_block: "7.5M"
    requests_per_second: 25
    block_increment: 500
    chunk_size: 80

  - contract_name: "ETHVault"
    function_name: totalAssets
    contract_address: "0x038c33792237F1575136110480142073129bB7e6"
    inputs:
      - []
    min_block: 25000000
    requests_per_second: 25
    block_increment: 500
    chunk_size: 80

  - contract_name: "BTCVault"
    function_name: totalAssets
    contract_address: "0xa6618dB1b8a869c3f2476dE116e861D818Bd2369"
    inputs:
      - []
    min_block: 25000000
    requests_per_second: 25
    block_increment: 500
    chunk_size: 80

  - contract_name: "ETHVault"
    function_name: exchangeRate
    contract_address: "0x038c33792237F1575136110480142073129bB7e6"
    inputs:
      - []
    min_block: 25000000
    requests_per_second: 25
    block_increment: 500
    chunk_size: 80

  - contract_name: "BTCVault"
    function_name: exchangeRate 
    contract_address: "0xa6618dB1b8a869c3f2476dE116e861D818Bd2369"
    inputs:
      - []
    min_block: 25000000
    requests_per_second: 25
    block_increment: 500
    chunk_size: 80