network_id: 84532
protocol: "synthetix"

blocks:
  min_block: "8M"
  requests_per_second: 1000
  block_increment: 500
  chunk_size: 80

eth_calls:
  - contract_name: "CoreProxy"
    package_name: "system"
    function_name: "getVaultCollateral"
    inputs:
      - [1, "0x8069c44244e72443722cfb22DcE5492cba239d39"]
    min_block: "8M"
    requests_per_second: 1000
    block_increment: 500
    chunk_size: 80

  - contract_name: "CoreProxy"
    package_name: "system"
    function_name: "getVaultDebt"
    inputs:
      - [1, "0x8069c44244e72443722cfb22DcE5492cba239d39"]
    min_block: "8M"
    requests_per_second: 1000
    block_increment: 500
    chunk_size: 80
