network_id: 1

blocks:
  min_block: "20000000"
  requests_per_second: 25
  block_increment: 150
  chunk_size: 50

eth_calls:
  - contract_name: "CoreProxy"
    package_name: "system"
    function_name: "getVaultCollateral"
    inputs:
      - [1, "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F"]
      - [8, "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F"]
    min_block: "20000000"
    requests_per_second: 25
    block_increment: 150
    chunk_size: 50

  - contract_name: "CoreProxy"
    package_name: "system"
    function_name: "getVaultDebt"
    inputs:
      - [1, "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F"]
      - [8, "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F"]
    min_block: "20000000"
    requests_per_second: 25
    block_increment: 150
    chunk_size: 50

  - contract_name: "TreasuryProxy"
    function_name: artificialDebt
    contract_address: "0x7b952507306E7D983bcFe6942Ac9F2f75C1332D8"
    inputs:
      - []
    min_block: 21800000
    requests_per_second: 25
    block_increment: 150
    chunk_size: 50
