version: "2.4"

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    networks:
      - data
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      PGDATA: /var/lib/postgresql/data
      POSTGRES_SHARED_BUFFERS: "4GB"
      POSTGRES_WORK_MEM: "100MB"
      POSTGRES_MAINTENANCE_WORK_MEM: "1GB"
      POSTGRES_EFFECTIVE_CACHE_SIZE: "8GB"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
      - ./parquet-data:/parquet-data
    ports:
      - "${DB_PORT}:5432"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8192M

  base-mainnet-processor:
    build:
      context: ./indexers/base-mainnet
    networks:
      - data
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: base_mainnet
      DB_PASS: $PG_PASSWORD
      RPC_ENDPOINT: https://mainnet.base.org

networks:
  data:
    driver: bridge
