version: 2
models:
  - name: block
    description: Block numbers and timestamps
    columns:
      - name: ts
        description: block timestamp in UTC
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
        description: unique block identifier
        tests:
          - not_null
          - unique
