version: 2

sources:
  - name: raw_base_sepolia
    database: analytics
    schema: raw_base_sepolia
    tables:
      - name: block

      - name: perps_market_proxy_event_account_created
      - name: perps_market_proxy_event_account_liquidation_attempt
      - name: perps_market_proxy_event_collateral_modified
      - name: perps_market_proxy_event_market_created
      - name: perps_market_proxy_event_market_updated
      - name: perps_market_proxy_legacy_event_market_updated
      - name: perps_market_proxy_event_order_committed
      - name: perps_market_proxy_legacy_event_order_committed
      - name: perps_market_proxy_event_order_settled
      - name: perps_market_proxy_event_position_liquidated
      - name: perps_market_proxy_event_previous_order_expired
      - name: perps_market_proxy_event_interest_rate_updated
      - name: perps_market_proxy_event_interest_charged

      - name: spot_market_proxy_event_order_committed
      - name: spot_market_proxy_event_order_settled
      - name: spot_market_proxy_event_order_cancelled
      - name: spot_market_proxy_event_synth_registered
      - name: spot_market_proxy_event_synth_bought
      - name: spot_market_proxy_event_synth_sold
      - name: spot_market_proxy_event_synth_wrapped
      - name: spot_market_proxy_event_synth_unwrapped

      - name: core_proxy_event_account_created
      - name: core_proxy_event_delegation_updated
      - name: core_proxy_event_deposited
      - name: core_proxy_event_withdrawn
      - name: core_proxy_event_liquidation
      - name: core_proxy_event_market_registered
      - name: core_proxy_event_pool_created
      - name: core_proxy_event_rewards_claimed
      - name: core_proxy_event_rewards_distributed
      - name: core_proxy_event_usd_burned
      - name: core_proxy_event_usd_minted
      - name: core_proxy_event_vault_liquidation
      - name: core_proxy_event_market_collateral_deposited
      - name: core_proxy_event_market_collateral_withdrawn
      - name: core_proxy_event_market_usd_deposited
      - name: core_proxy_event_market_usd_withdrawn
      - name: core_proxy_legacy_event_market_usd_deposited
      - name: core_proxy_legacy_event_market_usd_withdrawn

      - name: buyback_snx_event_buyback_processed

      - name: core_get_vault_collateral
      - name: core_get_vault_debt
      - name: blocks_parquet

  - name: raw_arbitrum_sepolia
    database: analytics
    schema: raw_arbitrum_sepolia
    tables:
      - name: block

      - name: spot_market_proxy_event_order_committed
      - name: spot_market_proxy_event_order_settled
      - name: spot_market_proxy_event_order_cancelled
      - name: spot_market_proxy_event_synth_registered
      - name: spot_market_proxy_event_synth_bought
      - name: spot_market_proxy_event_synth_sold
      - name: spot_market_proxy_event_synth_wrapped
      - name: spot_market_proxy_event_synth_unwrapped

      - name: core_proxy_event_account_created
      - name: core_proxy_event_delegation_updated
      - name: core_proxy_event_deposited
      - name: core_proxy_event_withdrawn
      - name: core_proxy_event_liquidation
      - name: core_proxy_event_market_registered
      - name: core_proxy_event_pool_created
      - name: core_proxy_event_rewards_claimed
      - name: core_proxy_event_rewards_distributed
      - name: core_proxy_event_usd_burned
      - name: core_proxy_event_usd_minted
      - name: core_proxy_event_vault_liquidation
      - name: core_proxy_event_market_collateral_deposited
      - name: core_proxy_event_market_collateral_withdrawn
      - name: core_proxy_event_market_usd_deposited
      - name: core_proxy_event_market_usd_withdrawn

      - name: core_get_vault_collateral
      - name: core_get_vault_debt
      - name: blocks_parquet

  - name: raw_base_mainnet
    database: analytics
    schema: raw_base_mainnet
    tables:
      - name: block

      - name: perps_market_proxy_event_account_created
      - name: perps_market_proxy_event_account_liquidation_attempt
      - name: perps_market_proxy_event_collateral_modified
      - name: perps_market_proxy_event_market_created
      - name: perps_market_proxy_event_market_updated
      - name: perps_market_proxy_legacy_event_market_updated
      - name: perps_market_proxy_event_order_committed
      - name: perps_market_proxy_legacy_event_order_committed
      - name: perps_market_proxy_event_order_settled
      - name: perps_market_proxy_event_position_liquidated
      - name: perps_market_proxy_event_previous_order_expired
      - name: perps_market_proxy_event_interest_rate_updated
      - name: perps_market_proxy_event_interest_charged

      - name: spot_market_proxy_event_order_committed
      - name: spot_market_proxy_event_order_settled
      - name: spot_market_proxy_event_order_cancelled
      - name: spot_market_proxy_event_synth_registered
      - name: spot_market_proxy_event_synth_bought
      - name: spot_market_proxy_event_synth_sold
      - name: spot_market_proxy_event_synth_wrapped
      - name: spot_market_proxy_event_synth_unwrapped

      - name: core_proxy_event_account_created
      - name: core_proxy_event_delegation_updated
      - name: core_proxy_event_deposited
      - name: core_proxy_event_withdrawn
      - name: core_proxy_event_liquidation
      - name: core_proxy_event_market_registered
      - name: core_proxy_event_pool_created
      - name: core_proxy_event_rewards_claimed
      - name: core_proxy_event_rewards_distributed
      - name: core_proxy_event_usd_burned
      - name: core_proxy_event_usd_minted
      - name: core_proxy_event_vault_liquidation
      - name: core_proxy_event_market_collateral_deposited
      - name: core_proxy_event_market_collateral_withdrawn
      - name: core_proxy_event_market_usd_deposited
      - name: core_proxy_event_market_usd_withdrawn
      - name: core_proxy_legacy_event_market_usd_deposited
      - name: core_proxy_legacy_event_market_usd_withdrawn

      - name: buyback_snx_legacy_event_buyback_processed
      - name: buyback_snx_event_buyback_processed

      - name: core_get_vault_collateral
      - name: core_get_vault_debt
      - name: blocks_parquet

  - name: raw_optimism_mainnet
    database: analytics
    schema: raw_optimism_mainnet
    tables:
      - name: block

      - name: spot_market_proxy_event_order_committed
      - name: spot_market_proxy_event_order_settled
      - name: spot_market_proxy_event_order_cancelled
      - name: spot_market_proxy_event_synth_registered
      - name: spot_market_proxy_event_synth_bought
      - name: spot_market_proxy_event_synth_sold
      - name: spot_market_proxy_event_synth_wrapped
      - name: spot_market_proxy_event_synth_unwrapped

      - name: core_proxy_event_account_created
      - name: core_proxy_event_delegation_updated
      - name: core_proxy_event_deposited
      - name: core_proxy_event_withdrawn
      - name: core_proxy_event_liquidation
      - name: core_proxy_event_market_registered
      - name: core_proxy_event_pool_created
      - name: core_proxy_event_rewards_claimed
      - name: core_proxy_event_rewards_distributed
      - name: core_proxy_event_usd_burned
      - name: core_proxy_event_usd_minted
      - name: core_proxy_event_vault_liquidation
      - name: core_proxy_event_market_collateral_deposited
      - name: core_proxy_event_market_collateral_withdrawn
