version: 2

sources:
  - name: raw_base_goerli
    database: analytics
    schema: raw_base_goerli
    tables:
      - name: perps_market_proxy_event_account_created
      - name: perps_market_proxy_event_account_liquidation_attempt
      - name: perps_market_proxy_event_collateral_modified
      - name: perps_market_proxy_event_market_created
      - name: perps_market_proxy_event_market_updated
      - name: perps_market_proxy_event_order_committed
      - name: perps_market_proxy_legacy_event_order_committed
      - name: perps_market_proxy_event_order_settled
      - name: perps_market_proxy_event_position_liquidated
      - name: perps_market_proxy_event_previous_order_expired

      - name: spot_market_proxy_event_order_committed
      - name: spot_market_proxy_event_order_settled
      - name: spot_market_proxy_event_order_cancelled
      - name: spot_market_proxy_event_synth_registered
      - name: spot_market_proxy_event_synth_bought
      - name: spot_market_proxy_event_synth_sold
      - name: spot_market_proxy_event_synth_wrapped
      - name: spot_market_proxy_event_synth_unwrapped

      - name: core_proxy_event_account_created
      - name: core_proxy_event_delegation_updated
      - name: core_proxy_event_deposited
      - name: core_proxy_event_withdrawn
      - name: core_proxy_event_liquidation
      - name: core_proxy_event_market_registered
      - name: core_proxy_event_pool_created
      - name: core_proxy_event_rewards_claimed
      - name: core_proxy_event_rewards_distributed
      - name: core_proxy_event_usd_burned
      - name: core_proxy_event_usd_minted
      - name: core_proxy_event_vault_liquidation
      - name: core_proxy_event_market_collateral_deposited
      - name: core_proxy_event_market_collateral_withdrawn
      - name: core_proxy_event_market_usd_deposited
      - name: core_proxy_event_market_usd_withdrawn

  - name: raw_base_sepolia
    database: analytics
    schema: raw_base_sepolia
    tables:
      - name: perps_market_proxy_event_account_created
      - name: perps_market_proxy_event_account_liquidation_attempt
      - name: perps_market_proxy_event_collateral_modified
      - name: perps_market_proxy_event_market_created
      - name: perps_market_proxy_event_market_updated
      - name: perps_market_proxy_event_order_committed
      - name: perps_market_proxy_legacy_event_order_committed
      - name: perps_market_proxy_event_order_settled
      - name: perps_market_proxy_event_position_liquidated
      - name: perps_market_proxy_event_previous_order_expired

      - name: spot_market_proxy_event_order_committed
      - name: spot_market_proxy_event_order_settled
      - name: spot_market_proxy_event_order_cancelled
      - name: spot_market_proxy_event_synth_registered
      - name: spot_market_proxy_event_synth_bought
      - name: spot_market_proxy_event_synth_sold
      - name: spot_market_proxy_event_synth_wrapped
      - name: spot_market_proxy_event_synth_unwrapped

      - name: core_proxy_event_account_created
      - name: core_proxy_event_delegation_updated
      - name: core_proxy_event_deposited
      - name: core_proxy_event_withdrawn
      - name: core_proxy_event_liquidation
      - name: core_proxy_event_market_registered
      - name: core_proxy_event_pool_created
      - name: core_proxy_event_rewards_claimed
      - name: core_proxy_event_rewards_distributed
      - name: core_proxy_event_usd_burned
      - name: core_proxy_event_usd_minted
      - name: core_proxy_event_vault_liquidation
      - name: core_proxy_event_market_collateral_deposited
      - name: core_proxy_event_market_collateral_withdrawn
      - name: core_proxy_event_market_usd_deposited
      - name: core_proxy_event_market_usd_withdrawn

  - name: raw_base_mainnet
    database: analytics
    schema: raw_base_mainnet
    tables:
      - name: perps_market_proxy_event_account_created
      - name: perps_market_proxy_event_account_liquidation_attempt
      - name: perps_market_proxy_event_collateral_modified
      - name: perps_market_proxy_event_market_created
      - name: perps_market_proxy_event_market_updated
      - name: perps_market_proxy_event_order_committed
      - name: perps_market_proxy_legacy_event_order_committed
      - name: perps_market_proxy_event_order_settled
      - name: perps_market_proxy_event_position_liquidated
      - name: perps_market_proxy_event_previous_order_expired

      - name: spot_market_proxy_event_order_committed
      - name: spot_market_proxy_event_order_settled
      - name: spot_market_proxy_event_order_cancelled
      - name: spot_market_proxy_event_synth_registered
      - name: spot_market_proxy_event_synth_bought
      - name: spot_market_proxy_event_synth_sold
      - name: spot_market_proxy_event_synth_wrapped
      - name: spot_market_proxy_event_synth_unwrapped

      - name: core_proxy_event_account_created
      - name: core_proxy_event_delegation_updated
      - name: core_proxy_event_deposited
      - name: core_proxy_event_withdrawn
      - name: core_proxy_event_liquidation
      - name: core_proxy_event_market_registered
      - name: core_proxy_event_pool_created
      - name: core_proxy_event_rewards_claimed
      - name: core_proxy_event_rewards_distributed
      - name: core_proxy_event_usd_burned
      - name: core_proxy_event_usd_minted
      - name: core_proxy_event_vault_liquidation
      - name: core_proxy_event_market_collateral_deposited
      - name: core_proxy_event_market_collateral_withdrawn
      - name: core_proxy_event_market_usd_deposited
      - name: core_proxy_event_market_usd_withdrawn

  - name: raw_optimism_goerli
    database: analytics
    schema: raw_optimism_goerli
    tables:
      - name: perps_market_proxy_event_account_created
      - name: perps_market_proxy_event_account_liquidated
      - name: perps_market_proxy_event_collateral_modified
      - name: perps_market_proxy_event_market_created
      - name: perps_market_proxy_event_market_updated
      - name: perps_market_proxy_event_order_committed
      - name: perps_market_proxy_event_order_settled
      - name: perps_market_proxy_event_position_liquidated
      - name: perps_market_proxy_event_previous_order_expired

      - name: spot_market_proxy_event_order_committed
      - name: spot_market_proxy_event_order_settled
      - name: spot_market_proxy_event_order_cancelled
      - name: spot_market_proxy_event_synth_registered
      - name: spot_market_proxy_event_synth_bought
      - name: spot_market_proxy_event_synth_sold
      - name: spot_market_proxy_event_synth_wrapped
      - name: spot_market_proxy_event_synth_unwrapped

      - name: core_proxy_event_account_created
      - name: core_proxy_event_delegation_updated
      - name: core_proxy_event_deposited
      - name: core_proxy_event_withdrawn
      - name: core_proxy_event_liquidation
      - name: core_proxy_event_market_registered
      - name: core_proxy_event_pool_created
      - name: core_proxy_event_rewards_claimed
      - name: core_proxy_event_rewards_distributed
      - name: core_proxy_event_usd_burned
      - name: core_proxy_event_usd_minted
      - name: core_proxy_event_vault_liquidation
      - name: core_proxy_event_market_collateral_deposited
      - name: core_proxy_event_market_collateral_withdrawn

  - name: raw_optimism_mainnet
    database: analytics
    schema: raw_optimism_mainnet
    tables:
      - name: spot_market_proxy_event_order_committed
      - name: spot_market_proxy_event_order_settled
      - name: spot_market_proxy_event_order_cancelled
      - name: spot_market_proxy_event_synth_registered
      - name: spot_market_proxy_event_synth_bought
      - name: spot_market_proxy_event_synth_sold
      - name: spot_market_proxy_event_synth_wrapped
      - name: spot_market_proxy_event_synth_unwrapped

      - name: core_proxy_event_account_created
      - name: core_proxy_event_delegation_updated
      - name: core_proxy_event_deposited
      - name: core_proxy_event_withdrawn
      - name: core_proxy_event_liquidation
      - name: core_proxy_event_market_registered
      - name: core_proxy_event_pool_created
      - name: core_proxy_event_rewards_claimed
      - name: core_proxy_event_rewards_distributed
      - name: core_proxy_event_usd_burned
      - name: core_proxy_event_usd_minted
      - name: core_proxy_event_vault_liquidation
      - name: core_proxy_event_market_collateral_deposited
      - name: core_proxy_event_market_collateral_withdrawn
