version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0

parameters:
  aws-region:
    type: string
    default: "us-east-1"
  ecr-repository:
    type: string
    default: "transformers-mage"

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      
      - aws-cli/setup:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          aws-region: << pipeline.parameters.aws-region >>
      
      # Build and push Docker image
      - aws-ecr/build-and-push-image:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: << pipeline.parameters.ecr-repository >>
          region: << pipeline.parameters.aws-region >>
          tag: "${CIRCLE_SHA1},latest"
          path: ./transformers-mage
          dockerfile: ./transformers-mage/Dockerfile

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push:
          context: aws-credentials
          filters:
            branches:
              only: main