apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: synthetix-data
data:
  # Aurora DB connection info - replace with actual values from your stack outputs
  db-host: "synthetix-prod-postgres-cluster.cluster-xxxxxxxxxxxx.us-east-1.rds.amazonaws.com"
  db-port: "5432"
  
  # Network RPC endpoints
  arbitrum-mainnet-rpc: "https://arb1.arbitrum.io/rpc"
  arbitrum-sepolia-rpc: "https://sepolia-rollup.arbitrum.io/rpc"
  base-mainnet-rpc: "https://mainnet.base.org"
  base-mainnet-lt-rpc: "https://mainnet.base.org"
  base-sepolia-rpc: "https://sepolia.base.org"
  eth-mainnet-rpc: "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  optimism-mainnet-rpc: "https://mainnet.optimism.io"
  optimism-mainnet-tlx-rpc: "https://mainnet.optimism.io"
  snax-mainnet-rpc: "https://mainnet.snaxchain.io/"
  snax-testnet-rpc: "https://testnet.snaxchain.io/"
  