apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1  # Change to your AWS region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: synthetix-data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: synthetix-data
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/EksExternalSecretsRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: indexer-service-account
  namespace: synthetix-data
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/EksIndexerServiceRole