version: 2

seeds:
  # reward distributors
  - name: arbitrum_mainnet_reward_distributors
    description: "Mapping of reward distributor addresses to their respective reward tokens"
    columns:
      - name: distributor_address
        description: "Address of the reward distributor contract"
        meta:
          type: string
        tests:
          - not_null
      - name: token_symbol
        description: "Symbol for the token received as reward"
        meta:
          type: string
        tests:
          - not_null
  - name: arbitrum_sepolia_reward_distributors
    description: "Mapping of reward distributor addresses to their respective reward tokens"
    columns:
      - name: distributor_address
        description: "Address of the reward distributor contract"
        meta:
          type: string
        tests:
          - not_null
      - name: token_symbol
        description: "Symbol for the token received as reward"
        meta:
          type: string
        tests:
          - not_null
  - name: base_mainnet_reward_distributors
    description: "Mapping of reward distributor addresses to their respective reward tokens"
    columns:
      - name: distributor_address
        description: "Address of the reward distributor contract"
        meta:
          type: string
        tests:
          - not_null
      - name: token_symbol
        description: "Symbol for the token received as reward"
        meta:
          type: string
        tests:
          - not_null
  - name: base_sepolia_reward_distributors
    description: "Mapping of reward distributor addresses to their respective reward tokens"
    columns:
      - name: distributor_address
        description: "Address of the reward distributor contract"
        meta:
          type: string
        tests:
          - not_null
      - name: token_symbol
        description: "Symbol for the token received as reward"
        meta:
          type: string
        tests:
          - not_null

  # tokens
  - name: arbitrum_mainnet_tokens
    description: "Mapping of common token addresses to their respective token symbols"
    columns:
      - name: token_address
        description: "Address of the token contract"
        meta:
          type: string
        tests:
          - not_null
      - name: token_symbol
        description: "Symbol for the token"
        meta:
          type: string
        tests:
          - not_null

  - name: arbitrum_sepolia_tokens
    description: "Mapping of common token addresses to their respective token symbols"
    columns:
      - name: token_address
        description: "Address of the token contract"
        meta:
          type: string
        tests:
          - not_null
      - name: token_symbol
        description: "Symbol for the token"
        meta:
          type: string
        tests:
          - not_null

  - name: base_mainnet_tokens
    description: "Mapping of common token addresses to their respective token symbols"
    columns:
      - name: token_address
        description: "Address of the token contract"
        meta:
          type: string
        tests:
          - not_null
      - name: token_symbol
        description: "Symbol for the token"
        meta:
          type: string
        tests:
          - not_null

  - name: base_sepolia_tokens
    description: "Mapping of common token addresses to their respective token symbols"
    columns:
      - name: token_address
        description: "Address of the token contract"
        meta:
          type: string
        tests:
          - not_null
      - name: token_symbol
        description: "Symbol for the token"
        meta:
          type: string
        tests:
          - not_null
