models:
  - name: fct_buyback_daily_base_sepolia
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: snx_amount
        data_type: numeric
      - name: usd_amount
        data_type: numeric
      - name: cumulative_snx_amount
        data_type: numeric
      - name: cumulative_usd_amount
        data_type: numeric
  - name: fct_buyback_hourly_base_sepolia
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: snx_amount
        data_type: numeric
      - name: usd_amount
        data_type: numeric
      - name: cumulative_snx_amount
        data_type: numeric
      - name: cumulative_usd_amount
        data_type: numeric
  - name: fct_buyback_base_sepolia
    columns:
      - name: id
        data_type: character varying
      - name: ts
        data_type: timestamp with time zone
      - name: buyer
        data_type: text
      - name: snx
        data_type: numeric
      - name: usd
        data_type: numeric
      - name: snx_price
        data_type: numeric
