version: 2
models:
  - name: core_account_created_arbitrum_sepolia
    description: AccountCreated events from the CoreProxy contract
    columns:
      - name: owner
        data_type: text
      - name: account_id
        data_type: numeric
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: transaction_hash
        data_type: text
      - name: block_number
        data_type: integer
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: event_name
        data_type: text
      - name: contract
        data_type: text
  - name: core_delegation_updated_arbitrum_sepolia
    description: DelegationUpdated events from the CoreProxy contract
    columns:
      - name: contract
        data_type: text
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: account_id
        data_type: numeric
      - name: collateral_type
        data_type: text
      - name: pool_id
        data_type: numeric
      - name: sender
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: leverage
        data_type: numeric
      - name: transaction_hash
        data_type: text
      - name: amount
        data_type: numeric
      - name: event_name
        data_type: text
  - name: core_deposited_arbitrum_sepolia
    description: Deposited events from the CoreProxy contract
    columns:
      - name: collateral_type
        data_type: text
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: contract
        data_type: text
      - name: event_name
        data_type: text
      - name: transaction_hash
        data_type: text
      - name: account_id
        data_type: numeric
      - name: sender
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: token_amount
        data_type: numeric
  - name: core_withdrawn_arbitrum_sepolia
    description: Withdrawn events from the CoreProxy contract
    columns:
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: contract
        data_type: text
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: token_amount
        data_type: numeric
      - name: collateral_type
        data_type: text
      - name: account_id
        data_type: numeric
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: sender
        data_type: text
      - name: event_name
        data_type: text
  - name: core_liquidation_arbitrum_sepolia
    description: Liquidation events from the CoreProxy contract
    columns:
      - name: pool_id
        data_type: numeric
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: contract
        data_type: text
      - name: event_name
        data_type: text
      - name: collateral_type
        data_type: text
      - name: sender
        data_type: text
      - name: liquidation_data
        data_type: jsonb
      - name: account_id
        data_type: numeric
      - name: transaction_hash
        data_type: text
      - name: liquidate_as_account_id
        data_type: numeric
  - name: core_market_updated_arbitrum_sepolia
    description: Combination of MarketCollateralDeposited,
      MarketCollateralWithdrawn, MarketUsdDeposited, MarketUsdWithdrawn events
      from the CoreProxy contract
    columns:
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: contract
        data_type: text
      - name: event_name
        data_type: text
      - name: market_id
        data_type: numeric
      - name: net_issuance
        data_type: numeric
      - name: deposited_collateral_value
        data_type: numeric
      - name: sender
        data_type: text
      - name: collateral_type
        data_type: text
      - name: credit_capacity
        data_type: numeric
      - name: token_amount
        data_type: numeric
  - name: core_market_registered_arbitrum_sepolia
    description: MarketRegistered events from the CoreProxy contract
    columns:
      - name: market
        data_type: text
      - name: market_id
        data_type: numeric
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: contract
        data_type: text
      - name: transaction_hash
        data_type: text
      - name: block_number
        data_type: integer
      - name: event_name
        data_type: text
      - name: sender
        data_type: text
  - name: core_pool_created_arbitrum_sepolia
    description: PoolCreated events from the CoreProxy contract
    columns:
      - name: contract
        data_type: text
      - name: sender
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: event_name
        data_type: text
      - name: owner
        data_type: text
      - name: pool_id
        data_type: numeric
  - name: core_rewards_claimed_arbitrum_sepolia
    description: RewardsClaimed events from the CoreProxy contract
    columns:
      - name: transaction_hash
        data_type: text
      - name: account_id
        data_type: numeric
      - name: collateral_type
        data_type: text
      - name: event_name
        data_type: text
      - name: contract
        data_type: text
      - name: amount
        data_type: numeric
      - name: distributor
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: pool_id
        data_type: numeric
      - name: block_number
        data_type: integer
  - name: core_rewards_distributed_arbitrum_sepolia
    description: RewardsDistributed events from the CoreProxy contract
    columns:
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: event_name
        data_type: text
      - name: amount
        data_type: numeric
      - name: start
        data_type: numeric
      - name: contract
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: transaction_hash
        data_type: text
      - name: collateral_type
        data_type: text
      - name: block_number
        data_type: integer
      - name: duration
        data_type: numeric
      - name: distributor
        data_type: text
      - name: pool_id
        data_type: numeric
  - name: core_usd_burned_arbitrum_sepolia
    description: UsdBurned events from the CoreProxy contract
    columns:
      - name: amount
        data_type: numeric
      - name: pool_id
        data_type: numeric
      - name: event_name
        data_type: text
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_number
        data_type: integer
      - name: account_id
        data_type: numeric
      - name: sender
        data_type: text
      - name: transaction_hash
        data_type: text
      - name: contract
        data_type: text
      - name: collateral_type
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
  - name: core_usd_minted_arbitrum_sepolia
    description: UsdMinted events from the CoreProxy contract
    columns:
      - name: pool_id
        data_type: numeric
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: account_id
        data_type: numeric
      - name: collateral_type
        data_type: text
      - name: block_number
        data_type: integer
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: sender
        data_type: text
      - name: amount
        data_type: numeric
      - name: event_name
        data_type: text
      - name: transaction_hash
        data_type: text
      - name: contract
        data_type: text
  - name: core_vault_liquidation_arbitrum_sepolia
    description: VaultLiquidation events from the CoreProxy contract
    columns:
      - name: transaction_hash
        data_type: text
      - name: collateral_type
        data_type: text
      - name: pool_id
        data_type: numeric
      - name: event_name
        data_type: text
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: liquidate_as_account_id
        data_type: numeric
      - name: liquidation_data
        data_type: jsonb
      - name: contract
        data_type: text
      - name: block_number
        data_type: integer
      - name: sender
        data_type: text
  - name: core_vault_collateral_arbitrum_sepolia
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: bigint
      - name: contract_address
        data_type: text
      - name: pool_id
        data_type: integer
      - name: collateral_type
        data_type: character varying
      - name: amount
        data_type: numeric
      - name: collateral_value
        data_type: numeric
  - name: core_vault_debt_arbitrum_sepolia
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: bigint
      - name: contract_address
        data_type: text
      - name: pool_id
        data_type: integer
      - name: collateral_type
        data_type: character varying
      - name: debt
        data_type: numeric
