name: synthetix
version: "1.0.0"
config-version: 2

profile: synthetix

# Configuring paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Variables
vars:
  vaults: ['eth', 'btc']
  v2_markets:
    [
      "1_inch",
      "aave",
      "ada",
      "algo",
      "ankr",
      "ape",
      "apt",
      "arb",
      "atom",
      "aud",
      "avax",
      "axs",
      "bal",
      "bch",
      "blur",
      "bnb",
      "bonk",
      "btc",
      "celo",
      "comp",
      "crv",
      "cvx",
      "doge",
      "dot",
      "dydx",
      "enj",
      "eos",
      "etc",
      "eth",
      "ethbtc",
      "eur",
      "fet",
      "fil",
      "floki",
      "flow",
      "ftm",
      "fxs",
      "gbp",
      "gmx",
      "grt",
      "icp",
      "imx",
      "inj",
      "jto",
      "jup",
      "knc",
      "ldo",
      "link",
      "ltc",
      "matic",
      "mav",
      "meme",
      "mkr",
      "near",
      "one",
      "op",
      "ordi",
      "pendle",
      "pepe",
      "perp",
      "pyth",
      "rndr",
      "rpl",
      "rune",
      "sei",
      "shib",
      "sol",
      "steth",
      "stetheth",
      "strk",
      "sui",
      "sushi",
      "tia",
      "trb",
      "trx",
      "uma",
      "uni",
      "usdt",
      "wld",
      "xag",
      "xau",
      "xlm",
      "xmr",
      "xrp",
      "xtz",
      "yfi",
      "zec",
      "zil",
      "zrx",
    ]
  tlx:
    [
      "eth_long1",
      "eth_short1",
      "eth_long2",
      "eth_short2",
      "eth_long5",
      "eth_short5",
      "btc_long1",
      "btc_short1",
      "btc_long2",
      "btc_short2",
      "btc_long5",
      "btc_short5",
      "sol_long1",
      "sol_short1",
      "sol_long2",
      "sol_short2",
      "sol_long5",
      "sol_short5",
      "link_long1",
      "link_short1",
      "link_long2",
      "link_short2",
      "link_long5",
      "link_short5",
      "op_long1",
      "op_short1",
      "op_long2",
      "op_short2",
      "op_long5",
      "op_short5",
      "eth_long3",
      "eth_short3",
      "eth_long4",
      "eth_short4",
      "btc_long3",
      "btc_short3",
      "btc_long4",
      "btc_short4",
      "sol_long3",
      "sol_short3",
      "sol_long4",
      "sol_short4",
      "pepe_long1",
      "pepe_short1",
      "pepe_long2",
      "pepe_short2",
      "pepe_long5",
      "pepe_short5",
      "doge_long2",
      "doge_short2",
      "doge_long5",
      "doge_short5",
      "eth_long7",
      "eth_short7",
      "btc_long7",
      "btc_short7",
      "ethbtc_long2",
      "ethbtc_short2",
      "ethbtc_long5",
      "ethbtc_short5",
      "sui_long2",
      "sui_short2",
      "sui_long5",
      "sui_short5",
      "ethbtc_long10",
      "ethbtc_short10",
      "sei_long2",
      "sei_short2",
      "sei_long5",
      "sei_short5",
      "rune_long2",
      "rune_short2",
      "rune_long5",
      "rune_short5",
    ]
  base_lt:
    [
      "eth_long3",
      "eth_short3",
      "btc_long3",
      "btc_short3",
      "sol_long3",
      "sol_short3",
      "xrp_long3",
      "xrp_short3",
      "pepe_long3",
      "pepe_short3",
      "doge_long3",
      "doge_short3",
      "wif_long3",
      "wif_short3",
      "pnut_long3",
      "pnut_short3",
      "bonk_long3",
      "bonk_short3",
      "fartcoin_long3",
      "fartcoin_short3",
      "trump_long3",
      "trump_short3",
    ]

tests:
  +severity: warn

models:
  synthetix:
    raw:
      eth:
        mainnet:
          +tags: "eth_mainnet"
          +schema: raw_eth_mainnet
      base:
        mainnet:
          +tags: "base_mainnet"
          +schema: raw_base_mainnet
        sepolia:
          +tags: "base_sepolia"
          +schema: raw_base_sepolia
      arbitrum:
        mainnet:
          +tags: "arbitrum_mainnet"
          +schema: raw_arbitrum_mainnet
        sepolia:
          +tags: "arbitrum_sepolia"
          +schema: raw_arbitrum_sepolia
      optimism:
        mainnet:
          +tags: "optimism_mainnet"
          +schema: raw_optimism_mainnet
      snax:
        testnet:
          +tags: "snax_testnet"
          +schema: raw_snax_testnet
        mainnet:
          +tags: "snax_mainnet"
          +schema: raw_snax_mainnet
    marts:
      cross_chains:
        +tags: "cross_chains"
        +schema: cross_chains
      eth:
        mainnet:
          +tags: "eth_mainnet"
          +schema: eth_mainnet
      base:
        mainnet:
          +tags: "base_mainnet"
          +schema: base_mainnet
        sepolia:
          +tags: "base_sepolia"
          +schema: base_sepolia
      arbitrum:
        mainnet:
          +tags: "arbitrum_mainnet"
          +schema: arbitrum_mainnet
        sepolia:
          +tags: "arbitrum_sepolia"
          +schema: arbitrum_sepolia
      optimism:
        mainnet:
          +tags: "optimism_mainnet"
          +schema: optimism_mainnet
seeds:
  synthetix:
    +schema: seeds
    tokens:
      arbitrum_mainnet_tokens:
        +column_types:
          token_address: text
          token_symbol: text
          yield_token_symbol: text
      base_mainnet_tokens:
        +column_types:
          token_address: text
          token_symbol: text
          yield_token_symbol: text
      eth_mainnet_tokens:
        +column_types:
          token_address: text
          token_symbol: text
          yield_token_symbol: text
      optimism_mainnet_tokens:
        +column_types:
          token_address: text
          token_symbol: text
          yield_token_symbol: text
    reward_distributors:
      eth_mainnet_reward_distributors:
        +column_types:
          reward_type: text
      base_mainnet_reward_distributors:
        +column_types:
          reward_type: text
      arbitrum_mainnet_reward_distributors:
        +column_types:
          reward_type: text
