name: synthetix
version: "1.0.0"
config-version: 2

profile: synthetix

# Configuring paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  synthetix:
    raw:
      core:
        enabled: "{{ target.name in ('base_sepolia', 'optimism_mainnet', 'base_mainnet', 'arbitrum_sepolia') }}"
      spot:
        enabled: "{{ target.name in ('base_sepolia', 'optimism_mainnet', 'base_mainnet') }}"
      perp:
        enabled: "{{ target.name in ('base_sepolia', 'base_mainnet') }}"
      buyback:
        enabled: "{{ target.name in ('base_mainnet', 'base_sepolia') }}"
    marts:
      core:
        enabled: "{{ target.name in ('base_sepolia', 'optimism_mainnet', 'base_mainnet', 'arbitrum_sepolia') }}"
      core_stat:
        enabled: "{{ target.name in ('base_sepolia', 'optimism_mainnet', 'base_mainnet', 'arbitrum_sepolia') }}"
      spot:
        enabled: "{{ target.name in ('base_sepolia', 'optimism_mainnet', 'base_mainnet') }}"
      perp:
        enabled: "{{ target.name in ('base_sepolia', 'base_mainnet') }}"
      perp_stats:
        enabled: "{{ target.name in ('base_sepolia', 'base_mainnet') }}"
      buyback:
        enabled: "{{ target.name in ('base_mainnet', 'base_sepolia') }}"
