name: synthetix
version: "1.0.0"
config-version: 2

profile: synthetix

# Configuring paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Variables
vars:
  v2_markets:
    [
      "1_inch",
      "aave",
      "ada",
      "algo",
      "ankr",
      "ape",
      "apt",
      "arb",
      "atom",
      "aud",
      "avax",
      "axs",
      "bal",
      "bch",
      "blur",
      "bnb",
      "bonk",
      "btc",
      "celo",
      "comp",
      "crv",
      "cvx",
      "doge",
      "dot",
      "dydx",
      "enj",
      "eos",
      "etc",
      "eth",
      "ethbtc",
      "eur",
      "fet",
      "fil",
      "floki",
      "flow",
      "ftm",
      "fxs",
      "gbp",
      "gmx",
      "grt",
      "icp",
      "imx",
      "inj",
      "jto",
      "jup",
      "knc",
      "ldo",
      "link",
      "ltc",
      "matic",
      "mav",
      "meme",
      "mkr",
      "near",
      "one",
      "op",
      "ordi",
      "pendle",
      "pepe",
      "perp",
      "pyth",
      "rndr",
      "rpl",
      "rune",
      "sei",
      "shib",
      "sol",
      "steth",
      "stetheth",
      "strk",
      "sui",
      "sushi",
      "tia",
      "trb",
      "trx",
      "uma",
      "uni",
      "usdt",
      "wld",
      "xag",
      "xau",
      "xlm",
      "xmr",
      "xrp",
      "xtz",
      "yfi",
      "zec",
      "zil",
      "zrx",
    ]

tests:
  +severity: warn

models:
  synthetix:
    analytics:
      base:
        +enabled: "{{ target.name != 'prod-op' }}"
        mainnet:
          +tags: "base_mainnet"
          +schema: analytics_base_mainnet
      eth:
        +enabled: "{{ target.name != 'prod-op' }}"
        mainnet:
          +tags: "eth_mainnet"
          +schema: analytics_eth_mainnet
    core:
      base:
        +enabled: "{{ target.name != 'prod-op' }}"
        mainnet:
          +tags: "base_mainnet"
          +schema: core_base_mainnet
      eth:
        +enabled: "{{ target.name != 'prod-op' }}"
        mainnet:
          +tags: "eth_mainnet"
          +schema: core_eth_mainnet
seeds:
  +schema: seeds
