dev:
  target: base_goerli
  outputs:
    base_goerli:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 23798
      dbname: analytics
      schema: base_goerli
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    optimism_goerli:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 23798
      dbname: analytics
      schema: optimism_goerli
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    optimism_mainnet:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 23798
      dbname: analytics
      schema: optimism_mainnet
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    base_mainnet:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 23798
      dbname: analytics
      schema: base_mainnet
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

docker:
  target: base_goerli
  outputs:
    base_goerli:
      type: postgres
      host: db
      user: postgres
      password: postgres
      port: 5432
      dbname: analytics
      schema: base_goerli
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    optimism_goerli:
      type: postgres
      host: db
      user: postgres
      password: postgres
      port: 5432
      dbname: analytics
      schema: optimism_goerli
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    optimism_mainnet:
      type: postgres
      host: db
      user: postgres
      password: postgres
      port: 5432
      dbname: analytics
      schema: optimism_mainnet
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    base_mainnet:
      type: postgres
      host: db
      user: postgres
      password: postgres
      port: 5432
      dbname: analytics
      schema: base_mainnet
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4
