synthetix:
  target: base_sepolia
  outputs:
    base_sepolia:
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('PG_PASSWORD') }}"
      port: 23798
      dbname: analytics
      schema: base_sepolia
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    optimism_mainnet:
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('PG_PASSWORD') }}"
      port: 23798
      dbname: analytics
      schema: optimism_mainnet
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    base_mainnet:
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('PG_PASSWORD') }}"
      port: 23798
      dbname: analytics
      schema: base_mainnet
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

docker:
  target: base_sepolia
  outputs:
    base_sepolia:
      type: postgres
      host: db
      user: postgres
      password: "{{ env_var('PG_PASSWORD') }}"
      port: 5432
      dbname: analytics
      schema: base_sepolia
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    optimism_mainnet:
      type: postgres
      host: db
      user: postgres
      password: "{{ env_var('PG_PASSWORD') }}"
      port: 5432
      dbname: analytics
      schema: optimism_mainnet
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4

    base_mainnet:
      type: postgres
      host: db
      user: postgres
      password: "{{ env_var('PG_PASSWORD') }}"
      port: 5432
      dbname: analytics
      schema: base_mainnet
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4
