synthetix:
  target: prod
  outputs:
    prod:
      type: postgres
      host: db
      user: postgres
      password: "{{ env_var('PG_PASSWORD') }}"
      port: 5432
      dbname: analytics
      schema: prod
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      threads: 4
