version: 2
model: null
models:
  - name: v2_perp_delayed_order_submitted_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: transaction_hash
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: contract
        data_type: text
      - name: market
        data_type: text
      - name: event_name
        data_type: text
      - name: account
        data_type: text
      - name: commit_deposit
        data_type: numeric
      - name: keeper_deposit
        data_type: numeric
      - name: executable_at_time
        data_type: numeric
      - name: intention_time
        data_type: numeric
      - name: target_round_id
        data_type: numeric
      - name: is_offchain
        data_type: boolean
      - name: size_delta
        data_type: numeric
      - name: tracking_code
        data_type: text
  - name: v2_perp_funding_recomputed_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: transaction_hash
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: contract
        data_type: text
      - name: market
        data_type: text
      - name: event_name
        data_type: text
      - name: index
        data_type: numeric
      - name: funding
        data_type: numeric
      - name: funding_rate
        data_type: numeric
  - name: v2_perp_margin_transferred_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: transaction_hash
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: contract
        data_type: text
      - name: market
        data_type: text
      - name: event_name
        data_type: text
      - name: account
        data_type: text
      - name: margin_delta
        data_type: numeric
  - name: v2_perp_position_liquidated_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: transaction_hash
        data_type: text
      - name: block_number
        data_type: integer
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: contract
        data_type: text
      - name: market
        data_type: text
      - name: event_name
        data_type: text
      - name: account
        data_type: text
      - name: liquidator
        data_type: text
      - name: stakers_fee
        data_type: numeric
      - name: liquidator_fee
        data_type: numeric
      - name: flagger_fee
        data_type: numeric
      - name: total_fee
        data_type: numeric
      - name: price
        data_type: numeric
  - name: v2_perp_position_modified_optimism_mainnet
    columns:
      - name: id
        data_type: character varying
      - name: transaction_hash
        data_type: text
      - name: contract
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: market
        data_type: text
      - name: event_name
        data_type: text
      - name: account
        data_type: text
      - name: funding_index
        data_type: numeric
      - name: last_price
        data_type: numeric
      - name: trade_size
        data_type: numeric
      - name: size
        data_type: numeric
      - name: margin
        data_type: numeric
      - name: fee
        data_type: numeric
      - name: skew
        data_type: numeric
