import {EvmBatchProcessor, EvmBatchProcessorFields, BlockHeader, Log as _Log, Transaction as _Transaction} from '@subsquid/evm-processor'
import * as coreProxyAbi from './abi/CoreProxy'
import * as accountProxyAbi from './abi/AccountProxy'
import * as spotMarketProxyAbi from './abi/SpotMarketProxy'
import * as perpsMarketProxyAbi from './abi/PerpsMarketProxy'
import * as perpsAccountProxyAbi from './abi/PerpsAccountProxy'

export const processor = new EvmBatchProcessor()
    .setDataSource({
        archive: 'https://v2.archive.subsquid.io/network/arbitrum-sepolia',
        chain: {
            url: 'https://sepolia-rollup.arbitrum.io/rpc',
            rateLimit: 15,
        },
    })
    .setFinalityConfirmation(1)
    .setBlockRange({from: 40_000_000})
    .setFields({
            log: {
                topics: true,
                data: true,
                transactionHash: true,
            },
            transaction: {
                hash: true,
                input: true,
                from: true,
                value: true,
                status: true,
        }
    })
    .addLog({
        address: ['0x76490713314fcec173f44e99346f54c6e92a8e42'],
        topic0: [
            coreProxyAbi.events['OwnerChanged'].topic,
            coreProxyAbi.events['OwnerNominated'].topic,
            coreProxyAbi.events['Upgraded'].topic,
            coreProxyAbi.events['FeatureFlagAllowAllSet'].topic,
            coreProxyAbi.events['FeatureFlagAllowlistAdded'].topic,
            coreProxyAbi.events['FeatureFlagAllowlistRemoved'].topic,
            coreProxyAbi.events['FeatureFlagDeniersReset'].topic,
            coreProxyAbi.events['FeatureFlagDenyAllSet'].topic,
            coreProxyAbi.events['AccountCreated'].topic,
            coreProxyAbi.events['PermissionGranted'].topic,
            coreProxyAbi.events['PermissionRevoked'].topic,
            coreProxyAbi.events['DebtAssociated'].topic,
            coreProxyAbi.events['AssociatedSystemSet'].topic,
            coreProxyAbi.events['CollateralLockCreated'].topic,
            coreProxyAbi.events['CollateralLockExpired'].topic,
            coreProxyAbi.events['Deposited'].topic,
            coreProxyAbi.events['Withdrawn'].topic,
            coreProxyAbi.events['CollateralConfigured'].topic,
            coreProxyAbi.events['TransferCrossChainInitiated'].topic,
            coreProxyAbi.events['IssuanceFeePaid'].topic,
            coreProxyAbi.events['UsdBurned'].topic,
            coreProxyAbi.events['UsdMinted'].topic,
            coreProxyAbi.events['Liquidation'].topic,
            coreProxyAbi.events['VaultLiquidation'].topic,
            coreProxyAbi.events['MarketCollateralDeposited'].topic,
            coreProxyAbi.events['MarketCollateralWithdrawn'].topic,
            coreProxyAbi.events['MaximumMarketCollateralConfigured'].topic,
            coreProxyAbi.events['MarketRegistered'].topic,
            coreProxyAbi.events['MarketSystemFeePaid'].topic,
            coreProxyAbi.events['MarketUsdDeposited'].topic,
            coreProxyAbi.events['MarketUsdWithdrawn'].topic,
            coreProxyAbi.events['SetMarketMinLiquidityRatio'].topic,
            coreProxyAbi.events['SetMinDelegateTime'].topic,
            coreProxyAbi.events['PoolApprovedAdded'].topic,
            coreProxyAbi.events['PoolApprovedRemoved'].topic,
            coreProxyAbi.events['PreferredPoolSet'].topic,
            coreProxyAbi.events['PoolCollateralConfigurationUpdated'].topic,
            coreProxyAbi.events['PoolCollateralDisabledByDefaultSet'].topic,
            coreProxyAbi.events['PoolConfigurationSet'].topic,
            coreProxyAbi.events['PoolCreated'].topic,
            coreProxyAbi.events['PoolNameUpdated'].topic,
            coreProxyAbi.events['PoolNominationRenounced'].topic,
            coreProxyAbi.events['PoolNominationRevoked'].topic,
            coreProxyAbi.events['PoolOwnerNominated'].topic,
            coreProxyAbi.events['PoolOwnershipAccepted'].topic,
            coreProxyAbi.events['PoolOwnershipRenounced'].topic,
            coreProxyAbi.events['SetMinLiquidityRatio'].topic,
            coreProxyAbi.events['RewardsClaimed'].topic,
            coreProxyAbi.events['RewardsDistributed'].topic,
            coreProxyAbi.events['RewardsDistributorRegistered'].topic,
            coreProxyAbi.events['RewardsDistributorRemoved'].topic,
            coreProxyAbi.events['NewSupportedCrossChainNetwork'].topic,
            coreProxyAbi.events['DelegationUpdated'].topic,
        ],
    })
    .addLog({
        address: ['0x1b791d05e437c78039424749243f5a79e747525e'],
        topic0: [
            accountProxyAbi.events['OwnerChanged'].topic,
            accountProxyAbi.events['OwnerNominated'].topic,
            accountProxyAbi.events['Upgraded'].topic,
            accountProxyAbi.events['Approval'].topic,
            accountProxyAbi.events['ApprovalForAll'].topic,
            accountProxyAbi.events['Transfer'].topic,
        ],
    })
    .addLog({
        address: ['0x93d645c42a0ca3e08e9552367b8c454765fff041'],
        topic0: [
            spotMarketProxyAbi.events['OwnerChanged'].topic,
            spotMarketProxyAbi.events['OwnerNominated'].topic,
            spotMarketProxyAbi.events['Upgraded'].topic,
            spotMarketProxyAbi.events['AssociatedSystemSet'].topic,
            spotMarketProxyAbi.events['DecayRateUpdated'].topic,
            spotMarketProxyAbi.events['MarketNominationRenounced'].topic,
            spotMarketProxyAbi.events['MarketOwnerChanged'].topic,
            spotMarketProxyAbi.events['MarketOwnerNominated'].topic,
            spotMarketProxyAbi.events['SynthImplementationSet'].topic,
            spotMarketProxyAbi.events['SynthImplementationUpgraded'].topic,
            spotMarketProxyAbi.events['SynthPriceDataUpdated'].topic,
            spotMarketProxyAbi.events['SynthRegistered'].topic,
            spotMarketProxyAbi.events['SynthetixSystemSet'].topic,
            spotMarketProxyAbi.events['SynthBought'].topic,
            spotMarketProxyAbi.events['SynthSold'].topic,
            spotMarketProxyAbi.events['OrderCancelled'].topic,
            spotMarketProxyAbi.events['OrderCommitted'].topic,
            spotMarketProxyAbi.events['OrderSettled'].topic,
            spotMarketProxyAbi.events['SettlementStrategyAdded'].topic,
            spotMarketProxyAbi.events['SettlementStrategySet'].topic,
            spotMarketProxyAbi.events['SynthUnwrapped'].topic,
            spotMarketProxyAbi.events['SynthWrapped'].topic,
            spotMarketProxyAbi.events['WrapperSet'].topic,
            spotMarketProxyAbi.events['AsyncFixedFeeSet'].topic,
            spotMarketProxyAbi.events['AtomicFixedFeeSet'].topic,
            spotMarketProxyAbi.events['CollateralLeverageSet'].topic,
            spotMarketProxyAbi.events['FeeCollectorSet'].topic,
            spotMarketProxyAbi.events['MarketSkewScaleSet'].topic,
            spotMarketProxyAbi.events['MarketUtilizationFeesSet'].topic,
            spotMarketProxyAbi.events['ReferrerShareUpdated'].topic,
            spotMarketProxyAbi.events['TransactorFixedFeeSet'].topic,
            spotMarketProxyAbi.events['WrapperFeesSet'].topic,
            spotMarketProxyAbi.events['FeatureFlagAllowAllSet'].topic,
            spotMarketProxyAbi.events['FeatureFlagAllowlistAdded'].topic,
            spotMarketProxyAbi.events['FeatureFlagAllowlistRemoved'].topic,
            spotMarketProxyAbi.events['FeatureFlagDeniersReset'].topic,
            spotMarketProxyAbi.events['FeatureFlagDenyAllSet'].topic,
        ],
    })
    .addLog({
        address: ['0xa73a7b754ec870b3738d0654ca75b7d0eebdb460'],
        topic0: [
            perpsMarketProxyAbi.events['AccountCreated'].topic,
            perpsMarketProxyAbi.events['PermissionGranted'].topic,
            perpsMarketProxyAbi.events['PermissionRevoked'].topic,
            perpsMarketProxyAbi.events['AssociatedSystemSet'].topic,
            perpsMarketProxyAbi.events['OwnerChanged'].topic,
            perpsMarketProxyAbi.events['OwnerNominated'].topic,
            perpsMarketProxyAbi.events['Upgraded'].topic,
            perpsMarketProxyAbi.events['FactoryInitialized'].topic,
            perpsMarketProxyAbi.events['MarketCreated'].topic,
            perpsMarketProxyAbi.events['CollateralModified'].topic,
            perpsMarketProxyAbi.events['DebtPaid'].topic,
            perpsMarketProxyAbi.events['InterestRateUpdated'].topic,
            perpsMarketProxyAbi.events['OrderCommitted'].topic,
            perpsMarketProxyAbi.events['PreviousOrderExpired'].topic,
            perpsMarketProxyAbi.events['AccountCharged'].topic,
            perpsMarketProxyAbi.events['InterestCharged'].topic,
            perpsMarketProxyAbi.events['MarketUpdated'].topic,
            perpsMarketProxyAbi.events['OrderSettled'].topic,
            perpsMarketProxyAbi.events['OrderCancelled'].topic,
            perpsMarketProxyAbi.events['FeatureFlagAllowAllSet'].topic,
            perpsMarketProxyAbi.events['FeatureFlagAllowlistAdded'].topic,
            perpsMarketProxyAbi.events['FeatureFlagAllowlistRemoved'].topic,
            perpsMarketProxyAbi.events['FeatureFlagDeniersReset'].topic,
            perpsMarketProxyAbi.events['FeatureFlagDenyAllSet'].topic,
            perpsMarketProxyAbi.events['AccountFlaggedForLiquidation'].topic,
            perpsMarketProxyAbi.events['AccountLiquidationAttempt'].topic,
            perpsMarketProxyAbi.events['AccountMarginLiquidation'].topic,
            perpsMarketProxyAbi.events['PositionLiquidated'].topic,
            perpsMarketProxyAbi.events['FundingParametersSet'].topic,
            perpsMarketProxyAbi.events['LiquidationParametersSet'].topic,
            perpsMarketProxyAbi.events['LockedOiRatioSet'].topic,
            perpsMarketProxyAbi.events['MarketPriceDataUpdated'].topic,
            perpsMarketProxyAbi.events['MaxLiquidationParametersSet'].topic,
            perpsMarketProxyAbi.events['MaxMarketSizeSet'].topic,
            perpsMarketProxyAbi.events['MaxMarketValueSet'].topic,
            perpsMarketProxyAbi.events['OrderFeesSet'].topic,
            perpsMarketProxyAbi.events['SettlementStrategyAdded'].topic,
            perpsMarketProxyAbi.events['SettlementStrategySet'].topic,
            perpsMarketProxyAbi.events['CollateralConfigurationSet'].topic,
            perpsMarketProxyAbi.events['CollateralLiquidateRewardRatioSet'].topic,
            perpsMarketProxyAbi.events['RewardDistributorRegistered'].topic,
            perpsMarketProxyAbi.events['FeeCollectorSet'].topic,
            perpsMarketProxyAbi.events['InterestRateParametersSet'].topic,
            perpsMarketProxyAbi.events['KeeperCostNodeIdUpdated'].topic,
            perpsMarketProxyAbi.events['KeeperRewardGuardsSet'].topic,
            perpsMarketProxyAbi.events['PerAccountCapsSet'].topic,
            perpsMarketProxyAbi.events['ReferrerShareUpdated'].topic,
        ],
    })
    .addLog({
        address: ['0xf3d4109eb4e7ec31f8eee5d9addad5f3c53a6c87'],
        topic0: [
            perpsAccountProxyAbi.events['OwnerChanged'].topic,
            perpsAccountProxyAbi.events['OwnerNominated'].topic,
            perpsAccountProxyAbi.events['Upgraded'].topic,
            perpsAccountProxyAbi.events['Approval'].topic,
            perpsAccountProxyAbi.events['ApprovalForAll'].topic,
            perpsAccountProxyAbi.events['Transfer'].topic,
        ],
    })

export type Fields = EvmBatchProcessorFields<typeof processor>
export type Block = BlockHeader<Fields>
export type Log = _Log<Fields>
export type Transaction = _Transaction<Fields>
