models:
  - name: fct_prices_base_mainnet
    columns:
      - name: ts
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: market_address
        description: "Market address"
        data_type: text
        tests:
          - not_null
      - name: market_symbol
        description: "Market symbol"
        data_type: text
        tests:
          - not_null
      - name: price
        description: "Price"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
  - name: fct_prices_hourly_base_mainnet
    columns:
      - name: ts
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: market_symbol
        description: "Market symbol"
        data_type: text
        tests:
          - not_null
      - name: price
        description: "Price"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
