models:
  - name: fct_buyback_daily_base_mainnet
    columns:
      - name: ts
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: snx_amount
        description: "Amount in SNX"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: usd_amount
        description: "Amount in USD"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: cumulative_snx_amount
        description: "Cumulative amount in SNX"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: cumulative_usd_amount
        description: "Cumulative amount in USD"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
  - name: fct_buyback_hourly_base_mainnet
    columns:
      - name: ts
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: snx_amount
        description: "Amount in SNX"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: usd_amount
        description: "Amount in USD"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: cumulative_snx_amount
        description: "Cumulative amount in SNX"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: cumulative_usd_amount
        description: "Cumulative amount in USD"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
  - name: fct_buyback_base_mainnet
    columns:
      - name: id
        description: "ID of the event record"
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: ts
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: buyer
        description: "Address of buyer"
        data_type: text
        tests:
          - not_null
      - name: snx
        description: "Amount in SNX"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: usd
        description: "Amount in USD"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: snx_price
        description: "SNX Price"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true