# Shared network-level configuration
network:
  network_id: 1
  archive_url: "https://v2.archive.subsquid.io/network/ethereum-mainnet"

protocols:
  synthetix:
    range:
      from: 20000000
    contracts_from_sdk:
      - name: CoreProxy
        package: system
      - name: AccountProxy
        package: system
      - name: SpotMarketProxy
        package: spotFactory
    contracts_from_abi:
      - name: LegacyMarketProxy
        address: "0x3AcF163B9E6a384D539e10dAc7e11213c638b2f5"
        abi: LegacyMarketProxy.json
    cannon_config:
      package: "synthetix-omnibus"
      version: "latest"
      preset: "main"