models:
  - name: fct_perp_trades_base_sepolia
    columns:
      - name: id
        data_type: character varying
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: contract
        data_type: text
      - name: market_id
        data_type: numeric
      - name: market_symbol
        data_type: text
      - name: account_id
        data_type: text
      - name: fill_price
        data_type: numeric
      - name: pnl
        data_type: numeric
      - name: accrued_funding
        data_type: numeric
      - name: trade_size
        data_type: numeric
      - name: position_size
        data_type: numeric
      - name: total_fees
        data_type: numeric
      - name: referral_fees
        data_type: numeric
      - name: collected_fees
        data_type: numeric
      - name: settlement_reward
        data_type: numeric
      - name: tracking_code
        data_type: text
      - name: settler
        data_type: text
      - name: notional_trade_size
        data_type: numeric
      - name: notional_position_size
        data_type: numeric
      - name: lp_fees
        data_type: numeric
      - name: exchange_fees
        data_type: numeric
  - name: fct_perp_pnl_base_sepolia
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: market_id
        data_type: integer
      - name: market_pnl
        data_type: numeric
  - name: fct_perp_orders_base_sepolia
    columns:
      - name: id
        data_type: character varying
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: contract
        data_type: text
      - name: market_id
        data_type: numeric
      - name: market_symbol
        data_type: text
      - name: account_id
        data_type: text
      - name: order_type
        data_type: integer
      - name: size
        data_type: numeric
      - name: acceptable_price
        data_type: numeric
      - name: settlement_time
        data_type: numeric
      - name: expiration_time
        data_type: numeric
      - name: tracking_code
        data_type: text
      - name: sender
        data_type: text
  - name: fct_perp_markets_base_sepolia
    columns:
      - name: id
        data_type: numeric
      - name: created_ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: market_symbol
        data_type: text
      - name: market_name
        data_type: text
  - name: fct_perp_market_history_base_sepolia
    columns:
      - name: id
        data_type: character varying
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: market_id
        data_type: numeric
      - name: market_symbol
        data_type: text
      - name: price
        data_type: numeric
      - name: skew
        data_type: numeric
      - name: size
        data_type: numeric
      - name: size_delta
        data_type: numeric
      - name: funding_rate
        data_type: numeric
      - name: funding_velocity
        data_type: numeric
      - name: interest_rate
        data_type: numeric
      - name: funding_rate_apr
        data_type: numeric
      - name: long_rate_apr
        data_type: numeric
      - name: short_rate_apr
        data_type: numeric
      - name: size_usd
        data_type: numeric
      - name: long_oi
        data_type: numeric
      - name: short_oi
        data_type: numeric
      - name: long_oi_pct
        data_type: numeric
      - name: short_oi_pct
        data_type: numeric
  - name: fct_perp_liq_position_base_sepolia
    columns:
      - name: id
        data_type: character varying
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
      - name: transaction_hash
        data_type: text
      - name: account_id
        data_type: text
      - name: market_id
        data_type: numeric
      - name: market_symbol
        data_type: text
      - name: amount_liquidated
        data_type: numeric
      - name: position_size
        data_type: numeric
  - name: fct_perp_liq_account_base_sepolia
    columns:
      - name: account_id
        data_type: text
      - name: ts
        data_type: timestamp with time zone
      - name: total_reward
        data_type: numeric
  - name: fct_perp_accounts_base_sepolia
    columns:
      - name: id
        data_type: character varying
      - name: created_ts
        data_type: timestamp with time zone
      - name: owner
        data_type: text
