version: 2
models:
  - name: core_account_created_arbitrum_mainnet
    description: AccountCreated events from the CoreProxy contract
    columns:
      - name: owner
        description: "Address of the account owner"
        data_type: text
        tests:
          - not_null
      - name: account_id
        description: "ID of the account"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: id
        description: "ID of the event record"
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: transaction_hash
        description: "Transaction hash"
        data_type: text
        tests:
          - not_null
      - name: block_number
        description: "Block number"
        data_type: integer
        tests:
          - not_null
      - name: block_timestamp
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
          - dbt_utils.recency:
              date_part: day
              field: ts
              interval: 1 
              config: 
                severity: warn
      - name: event_name
        description: "Event name"
        data_type: text
        tests:
          - not_null
          - accepted_value:
              values: ["AccountCreated"] 
      - name: contract
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null
  - name: core_delegation_updated_arbitrum_mainnet
    description: DelegationUpdated events from the CoreProxy contract
    columns:
      - name: contract
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null
      - name: id
        description: "ID of the event record"
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: account_id
        description: "ID of the account"
        data_type: numeric
        tests:
          - not_null
      - name: collateral_type
        description: "Type of delegated collateral"
        data_type: text
        tests:
          - not_null
      - name: pool_id
        description: "ID of the pool"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: sender
        description: "Address of the delegator"
        data_type: text
        tests:
          - not_null
      - name: block_timestamp
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: block_number
        description: "Block number"
        data_type: integer
        tests:
          - not_null
      - name: leverage
        description: "Leverage"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1000000000000000000
              max_value: 1000000000000000000
              inclusive: true
      - name: transaction_hash
        description: "Transaction hash"
        data_type: text
        tests:
          - not_null
      - name: amount
        description: "Amount delegated"
        data_type: numeric
        tests:
          - not_null
      - name: event_name
        description: "Event name"
        data_type: text
        tests:
          - not_null
          - accepted_value:
              values: ["DelegationUpdated"] 
  - name: core_deposited_arbitrum_mainnet
    description: Deposited events from the CoreProxy contract
    columns:
      - name: collateral_type
        description: "Type of delegated collateral"
        data_type: text
        tests:
          - not_null
      - name: id
        description: "ID of the event record"
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: contract
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null
      - name: event_name
        description: "Event name"
        data_type: text
        tests:
          - not_null
          - accepted_value:
              values: ["Deposited"] 
      - name: transaction_hash
        description: "Transaction hash"
        data_type: text
        tests:
          - not_null
      - name: account_id
        description: "ID of the account"
        data_type: numeric
        tests:
          - not_null
      - name: sender
        description: "Address of the depositor"
        data_type: text
        tests:
          - not_null
      - name: block_timestamp
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: block_number
        description: "Block number"
        data_type: integer
        tests:
          - not_null
      - name: token_amount
        description: "Token amount deposited"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
  - name: core_withdrawn_arbitrum_mainnet
    description: Withdrawn events from the CoreProxy contract
    columns:
      - name: block_timestamp
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: contract
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null
      - name: block_number
        description: "Block number"
        data_type: integer
        tests:
          - not_null
      - name: transaction_hash
        description: "Transaction hash"
        data_type: text
        tests:
          - not_null
      - name: token_amount
        description: "Token amount withdrawn"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: collateral_type
        description: "Type of delegated collateral"
        data_type: text
        tests:
          - not_null
      - name: account_id
        description: "ID of the account"
        data_type: numeric
        tests:
          - not_null
      - name: id
        description: "ID of the event record"
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: sender
        description: "Address of the withdrawer"
        data_type: text
        tests:
          - not_null
      - name: event_name
        description: "Event name"
        data_type: text
        tests:
          - not_null
          - accepted_value:
              values: ["Withdrawn"] 
  - name: core_liquidation_arbitrum_mainnet
    description: Liquidation events from the CoreProxy contract
    columns:
      - name: pool_id
        description: "ID of the pool"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: block_timestamp
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: block_number
        description: "Block number"
        data_type: integer
        tests:
          - not_null
      - name: id
        description: "ID of the event record"
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: contract
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null
      - name: event_name
        description: "Event name"
        data_type: text
        tests:
          - not_null
          - accepted_value:
              values: ["Liquidation"] 
      - name: collateral_type
        description: "Type of delegated collateral"
        data_type: text
        tests:
          - not_null
      - name: sender
        description: "Address of the liquidator"
        data_type: text
        tests:
          - not_null
      - name: liquidation_data
        data_type: jsonb
      - name: account_id
        description: "ID of the account"
        data_type: numeric
        tests:
          - not_null
      - name: transaction_hash
        description: "Transaction hash"
        data_type: text
        tests:
          - not_null
      - name: liquidate_as_account_id
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
  - name: core_market_updated_arbitrum_mainnet
    description: >
      Combination of MarketCollateralDeposited, MarketCollateralWithdrawn, 
      MarketUsdDeposited, MarketUsdWithdrawn events from the CoreProxy contract
    columns:
      - name: id
        description: "ID of the event record"
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_timestamp
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: block_number
        description: "Block number"
        data_type: integer
        tests:
          - not_null
      - name: transaction_hash
        description: "Transaction hash"
        data_type: text
        tests:
          - not_null
      - name: contract
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null
      - name: event_name
        description: "Event name"
        data_type: text
        tests:
          - not_null
          - accepted_value:
              values: ["Liquidation"] 
      - name: market_id
        description: "ID of the market"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: net_issuance
        description: "Net issuance"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: deposited_collateral_value
        description: "Deposited collateral value"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: sender
        description: "Address of the event initiator"
        data_type: text
        tests:
          - not_null
      - name: collateral_type
        description: "Type of delegated collateral"
        data_type: text
        tests:
          - not_null
      - name: credit_capacity
        description: "Credit capacity"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: token_amount
        description: "Token amount"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
  - name: core_market_registered_arbitrum_mainnet
    description: MarketRegistered events from the CoreProxy contract
    columns:
      - name: market
        description: "Market name"
        data_type: text
        tests:
          - not_null
      - name: market_id
        description: "Market ID"
        data_type: numeric
        tests:
          - not_null
          - unique
      - name: id
        description: "ID of the event record"
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_timestamp
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: contract
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null
      - name: transaction_hash
        description: "Transaction hash"
        data_type: text
        tests:
          - not_null
      - name: block_number
        description: "Block number"
        data_type: integer
        tests:
          - not_null
      - name: event_name
        description: "Event name"
        data_type: text
        tests:
          - not_null
          - accepted_value:
              values: ["MarketRegistered"] 
      - name: sender
        description: "Address of the event initiator"
        data_type: text
        tests:
          - not_null
  - name: core_pool_created_arbitrum_mainnet
    description: "PoolCreated events from the CoreProxy contract"
    columns:
      - name: contract
        description: "Address of the contract"
        data_type: text
        tests:
          - not_null
      - name: sender
        description: "Address of the event initiator"
        data_type: text
        tests:
          - not_null
      - name: block_timestamp
        description: "Block timestamp"
        data_type: timestamp with time zone
        tests:
          - not_null
      - name: id
        description: "ID of the event record"
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_number
        description: "Block number"
        data_type: integer
        tests:
          - not_null
      - name: transaction_hash
        description: "Transaction hash"
        data_type: text
        tests:
          - not_null
      - name: event_name
        description: "Event name"
        data_type: text
        tests:
          - not_null
          - accepted_value:
              values: ["MarketRegistered"] 
      - name: owner
        description: "Address of the pool owner"
        data_type: text
        tests:
          - not_null
      - name: pool_id
        description: "ID of the pool"
        data_type: numeric
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
  - name: core_rewards_claimed_arbitrum_mainnet
    description: RewardsClaimed events from the CoreProxy contract
    columns:
      - name: transaction_hash
        data_type: text
      - name: account_id
        data_type: numeric
      - name: collateral_type
        data_type: text
      - name: event_name
        data_type: text
      - name: contract
        data_type: text
      - name: amount
        data_type: numeric
      - name: distributor
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: pool_id
        data_type: numeric
      - name: block_number
        data_type: integer
  - name: core_rewards_distributed_arbitrum_mainnet
    description: RewardsDistributed events from the CoreProxy contract
    columns:
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: event_name
        data_type: text
      - name: amount
        data_type: numeric
      - name: start
        data_type: numeric
      - name: contract
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: transaction_hash
        data_type: text
      - name: collateral_type
        data_type: text
      - name: block_number
        data_type: integer
      - name: duration
        data_type: numeric
      - name: distributor
        data_type: text
      - name: pool_id
        data_type: numeric
  - name: core_usd_burned_arbitrum_mainnet
    description: UsdBurned events from the CoreProxy contract
    columns:
      - name: amount
        data_type: numeric
      - name: pool_id
        data_type: numeric
      - name: event_name
        data_type: text
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_number
        data_type: integer
      - name: account_id
        data_type: numeric
      - name: sender
        data_type: text
      - name: transaction_hash
        data_type: text
      - name: contract
        data_type: text
      - name: collateral_type
        data_type: text
      - name: block_timestamp
        data_type: timestamp with time zone
  - name: core_usd_minted_arbitrum_mainnet
    description: UsdMinted events from the CoreProxy contract
    columns:
      - name: pool_id
        data_type: numeric
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: account_id
        data_type: numeric
      - name: collateral_type
        data_type: text
      - name: block_number
        data_type: integer
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: sender
        data_type: text
      - name: amount
        data_type: numeric
      - name: event_name
        data_type: text
      - name: transaction_hash
        data_type: text
      - name: contract
        data_type: text
  - name: core_vault_liquidation_arbitrum_mainnet
    description: VaultLiquidation events from the CoreProxy contract
    columns:
      - name: transaction_hash
        data_type: text
      - name: collateral_type
        data_type: text
      - name: pool_id
        data_type: numeric
      - name: event_name
        data_type: text
      - name: id
        data_type: character varying
        tests:
          - not_null
          - unique
      - name: block_timestamp
        data_type: timestamp with time zone
      - name: liquidate_as_account_id
        data_type: numeric
      - name: liquidation_data
        data_type: jsonb
      - name: contract
        data_type: text
      - name: block_number
        data_type: integer
      - name: sender
        data_type: text
  - name: core_vault_collateral_arbitrum_mainnet
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: bigint
      - name: contract_address
        data_type: text
      - name: pool_id
        data_type: integer
      - name: collateral_type
        data_type: character varying
      - name: amount
        data_type: numeric
      - name: collateral_value
        data_type: numeric
  - name: core_vault_debt_arbitrum_mainnet
    columns:
      - name: ts
        data_type: timestamp with time zone
      - name: block_number
        data_type: bigint
      - name: contract_address
        data_type: text
      - name: pool_id
        data_type: integer
      - name: collateral_type
        data_type: character varying
      - name: debt
        data_type: numeric
