# Shared network-level configuration
network:
  network_id: 8453
  archive_url: "https://v2.archive.subsquid.io/network/base-mainnet"

configs:
  default:
    range:
      from: 7500000
      to: latest
    contracts_from_sdk:
      - name: CoreProxy
        package: system
      - name: AccountProxy
        package: system
      - name: SpotMarketProxy
        package: spotFactory
      - name: PerpsMarketProxy
        package: perpsFactory
      - name: PerpsAccountProxy
        package: perpsFactory
      - name: buyback_snx
        package: buyback_snx
    contracts_from_abi:
      - name: CoreProxyLegacy
        abi: ./abi/CoreProxyLegacy.json
      - name: PerpsMarketProxyLegacy
        abi: ./abi/PerpsMarketProxyLegacy.json
      - name: BuybackSnxLegacy
        abi: ./abi/BuybackSnxLegacy.json
    cannon_config:
      package: "synthetix-omnibus"
      version: "latest"
      preset: "andromeda"

  base_mainnet_parquet:
    target:
      type: parquet
      path: "/parquet-data/base_mainnet_parquet"
    range:
      from: 20000000
      to: 20200000
    contracts_from_sdk:
      - name: CoreProxy
        package: system
      - name: AccountProxy
        package: system
      - name: SpotMarketProxy
        package: spotFactory
      - name: PerpsMarketProxy
        package: perpsFactory
      - name: PerpsAccountProxy
        package: perpsFactory
      - name: buyback_snx
        package: buyback_snx
    contracts_from_abi:
      - name: CoreProxyLegacy
        abi: ./abi/CoreProxyLegacy.json
      - name: PerpsMarketProxyLegacy
        abi: ./abi/PerpsMarketProxyLegacy.json
      - name: BuybackSnxLegacy
        abi: ./abi/BuybackSnxLegacy.json
    cannon_config:
      package: "synthetix-omnibus"
      version: "latest"
      preset: "andromeda"