# Shared network-level configuration
network:
  network_id: 42161
  archive_url: "https://v2.archive.subsquid.io/network/arbitrum-one"

configs:
  synthetix-v3:
    range:
      from: 218000000
      to: latest
    contracts_from_sdk:
      - name: CoreProxy
        package: system
      - name: AccountProxy
        package: system
      - name: SpotMarketProxy
        package: spotFactory
      - name: PerpsMarketProxy
        package: perpsFactory
      - name: PerpsAccountProxy
        package: perpsFactory

  curve_usdx:
    range:
      from: 236000000
      to: latest
    contracts_from_abi:
      - name: CurveUSDx
        abi: ./abi/CurveUSDx.json
