arbitrum_mainnet:
  archive_url: "https://v2.archive.subsquid.io/network/arbitrum-one"
  range:
    from: 218000000
  contracts_from_sdk:
    - name: CoreProxy
      package: system
    - name: AccountProxy
      package: system
    - name: SpotMarketProxy
      package: spotFactory
    - name: PerpsMarketProxy
      package: perpsFactory
    - name: PerpsAccountProxy
      package: perpsFactory
  network_id: 42161