select
    ts,
    block_number,
    contract_address,
    pool_id,
    collateral_type,
    amount,
    collateral_value
from
    "analytics"."prod_raw_base_mainnet"."core_vault_collateral_base_mainnet"