# Shared network-level configuration
network:
  network_id: 42161
  archive_url: "https://v2.archive.subsquid.io/network/arbitrum-one"

configs:
  synthetix:
    range:
      from: 218000000
    contracts_from_sdk:
      - name: CoreProxy
        package: system
      - name: AccountProxy
        package: system
      - name: SpotMarketProxy
        package: spotFactory
      - name: PerpsMarketProxy
        package: perpsFactory
      - name: PerpsAccountProxy
        package: perpsFactory

  curve:
    range:
      from: 236000000
    contracts_from_abi:
      - name: CurveUsdx
        address: '0x096A8865367686290639bc50bF8D85C0110d9Fea'
        abi: ./abi/CurvePool.json
