version: 2
models:
  - name: blocks_arbitrum_mainnet
    description: Block numbers and timestamps
    columns:
      - name: ts
        description: UTC timestamp
        data_type: timestamp with time zone
      - name: block_number
        data_type: integer
        description: Block height
        tests:
          - not_null
          - unique
