version: 2
models:
  - name: blocks_arbitrum_mainnet
    description: Block numbers and timestamps
    columns:
      - name: ts
        description: UTC timestamp
        data_type: timestamp with time zone
      - name: block_number
        description: Block height
        data_type: integer
        tests:
          - not_null
          - unique
          - dbt_utils.recency:
              date_part: hour
              field: ts
              interval: 1 
          - dbt_utils.sequential_values:
              interval: 1
