name: Lint Transformer Models

on:
  push:
    branches:
      - main
      - 'transformers/**'

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "actions/setup-python@v3"
        with:
            python-version: "3.10.11"
      - name: Install SQLFluff
        run: "pip install sqlfluff"
      - name: Lint models
        run: "diff-quality --violations=sqlfluff --compare-branch main --fail-under 100"
